### ISSUE TITLE
Wrong URL for repo org

### ISSUE THREAD

**Issue by IRTermite** [osic/osic-clouds#1]
Posted as: https://github.com/osic/osic-clouds  <-- So redundant...
Should be: https://github.com/osic/

**Comment by mrhillsman** [comment]
Do you have access to rename?

**Comment by IRTermite** [comment]
Yup... just setting a reminder to myself.

**Comment by IRTermite** [comment]
Hey @mrhillsman ... while you mention permissions... it is telling me I don't have write to my own repo now... 1) I was trying to click on the wiki link to get that built 2) I tried to use "add new file" through the gui just to see if things weren't jacked before I start doing pushes again.

**Comment by mrhillsman** [comment]
Not sure what happened; we got it resolved though :)
