### ISSUE TITLE
Cloud1 network inaccessible when instances are connected to GATEWAY_NET/GATEWAY_NET_V6

### ISSUE THREAD

**Issue by iamanush** [osic/osic-clouds#2]
My instances became inaccessible starting Tuesday this week. On further investigation, as long as my router/network was connected through the GATEWAY_NET or GATEWAY_NET_V6, I was unable to ping my external floating ip.

My workaround was to move my net under a different OSIC_SHARED_X router.

**Comment by IRTermite** [comment]
Ah... yes... there was an email sent to all users about this a while ago from me. Look for "The Langoliers Are Coming"

GATEWAY_NET_V6 won't have floating IPs and you shouldn't need a router on it. The v6 IP on it is publicly routable, and the v4 IP on their is for internal comms between nodes.

Everyone should be using the OSIC_SHARED_X router and not creating new ones. Creating new routers wastes IP's from the pool.

@cloudnull has much more detail on this.

**Comment by cloudnull** [comment]
Hi @iamanush I'd be happy to go into more detail which we can cover on Vidyo or in IRC within the #osic-clouds channel. The TL;DR on this is going forward people will need to use the _OSIC_SHARED_X_ routers. Personal routers will be decommissioned or will have the gateway interface moved to the "**GATEWAY_NET_V6**". Connecting routers to "**GATEWAY_NET**" to a routers gateway interface unnecessarily consume precious public IPv4 space which we are running very close to being out of. If you were already using one of the _OSIC_SHARED_X_ please let me know which router was seemingly causing the issue (the router name and/or UUID). Additionally do we know if others on the same router were effected by this issue; maybe this was a case of a noisy neighbor? 

All that said, I'm glad you've been able to fix the issue by moving to a shared router and should you have any further questions please feel free to reach out.

**FYI**: the next round of router decommissions within the OSIC project will take place next week. Please let people know that networks not moved off a personal router it may be disconnected for active floating IP addresses.

**Comment by iamanush** [comment]
@cloudnull This all makes sense. Thanks much. I haven't extensively gone and asked if others have been affected.
