### ISSUE TITLE
Wiki specified in README does not exist

### ISSUE THREAD

**Issue by JohnVillalovos** [osic/osic-clouds#3]
The wiki specified in the README does not exist.

It says to go to:
https://github.com/osic/osic-clouds/blob/master/OSIC%20Cluster%20Wiki

Which says page not found.

**Comment by IRTermite** [comment]
Thank you. I will take a look soon. Maybe it is just a broken link.

**Comment by IRTermite** [comment]
Yea, I had the link format backwards and git read it wrong. Fixed.

**Comment by JohnVillalovos** [comment]
There is also a wiki link at the bottom of the readme. In the Getting Started section
