### ISSUE TITLE
Default openrc file should specify OS_IDENTITY_API_VERSION=3

### ISSUE THREAD

**Issue by JohnVillalovos** [osic/osic-clouds#4]
Seems like the cloud is using API version 3. But not specifying that in the default openrc file.

Should add:
  `export OS_IDENTITY_API_VERSION=3`

**Comment by IRTermite** [comment]
I'll talk with @cloudnull and see what we find. Thank you.

**Comment by cloudnull** [comment]
Which RC file are we talking about? If this is something coming from horizon there's little we can do to change it other than working with upstream teams. If this is something that we're providing then we should change it.

**Comment by IRTermite** [comment]
I believe it is the one exported from Horizon @cloudnull , which is why I mentioned you here; because I wasn't aware that we were offering one up any other way or not. Sounds like we aren't. In that case, sorry @JohnVillalovos but this is an OpenStack thing, not an environment thing.

Interesting though... I see where my openrc contains the correct 'export OS_AUTH_URL' for v3, but no 'OS_IDENTITY_API_VERSION'. But, it works just fine when issuing commands.

Curious... What lead you to determining this an issue?

**Comment by JohnVillalovos** [comment]
@cloudnull 
I downloaded the file from:
https://cloud1.osic.org/project/access_and_security/api_access/openrc/

From the page:
https://cloud1.osic.org/project/access_and_security/

And then API Access

**Comment by JohnVillalovos** [comment]
@IRTermite 

When I ran: "openstack server list" I got an error.

$ openstack server list
Expecting to find domain in user - the server could not comply with the request since it is either malformed or otherwise incorrect. The client is assumed to be in error. (HTTP 400) (Request-ID: req-f6951da3-1e27-4418-a1cc-1a442e6222d7)

Adding:
OS_IDENTITY_API_VERSION=3

Made everything work.

**Comment by IRTermite** [comment]
Interesting. Looks like it is already identified and being looked at.

https://review.openstack.org/#/c/186846
https://bugs.launchpad.net/horizon/+bug/1547061

**Comment by cloudnull** [comment]
@JohnVillalovos I'd recommend you setup a clouds.yml file as noted here: "http://docs.openstack.org/developer/python-openstackclient/configuration.html". Here is an example of my config

# ~/.config/openstack/clouds.yaml

``` yaml
clouds:
  osic-mine:
    auth:
      auth_url: https://cloud1.osic.org:5000
      project_name: MINE  # Change this
      username: MINE_TOO  # Change this
      password: MINE_ALSO  # Change this
    region_name: RegionOne
```

With that set I can specify the clouds I wish to work with by passing the name of the cloud into the openstack command. 

``` bash
$ openstack  --os-cloud osic-mine server list
```

**Comment by JohnVillalovos** [comment]
@cloudnull Thanks for the info
