### ISSUE TITLE
some issue with authorization

### ISSUE THREAD

**Issue by manjeetbhati** [osic/osic-clouds#5]
I was trying to login into osic cloud dashboard and sometimes it just returned error message authorized projects not found, after few minutes same password which i previously copied worked for login

**Comment by IRTermite** [comment]
When was this? I don't want to assume it was related to the networking issues we had today, but it is likely we could have been doing work for a split moment at that time.

**Comment by manjeetbhati** [comment]
it was some time today b/w 1:30 to 2:10 pm (PST),

**Comment by IRTermite** [comment]
Confirmed can replicate.
First attempt to log in (authorized projects not found).
Second attempt to log in same message).
Close tab.
New tab.
Third attempt (success).

Thoughts, @cloudnull ?

I would suggest you not looking into this until tomorrow though; you've been at it all day with the other issues.

**Comment by manjeetbhati** [comment]
I guess it took me more than 2 attempts to get into it, but it was exactly same error message I was getting

**Comment by cloudnull** [comment]
Anyone running into authentication problems is advised to retry. It would seem that there's a performance regression in keystone w/ mitaka. In looking at our work loads the issues seem to be inline with Matt Fishers findings as outlined here: [ http://www.mattfischer.com/blog/?p=703 ]. In the coming day or so I'll be reaching out to some keystone folks to ensure we have the most performant cluster possible.

**Comment by cloudnull** [comment]
I believe this has been resolved. We updated our horizon containers and it looks like the issue is now gone. Please confirm.

**Comment by manjeetbhati** [comment]
i  tried logging in multiple times, I was able to get into dashboard on first attempt when password was correct, all the times.
